/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BackgroundManager: typeof import("../hooks/head/bgManager.js").BackgroundManager
  const BlessYouEn: typeof import('../hooks/head/blessyou-en.mjs').BlessYouEn
  const DownloadPCM: typeof import('../utils/baseToaudio').DownloadPCM
  const DynamicBones: typeof import('../hooks/head/dynamicbones.mjs').DynamicBones
  const GradientBackground: typeof import("../hooks/head/bgManager.js").GradientBackground
  const Link: typeof import('react-router-dom').Link
  const LipsyncEn: typeof import("../hooks/head/blessyou-en.mjs").LipsyncEn
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const TalkingHead: typeof import('../hooks/head/blessyouhead.mjs').TalkingHead
  const addSpeaker: typeof import("../api/index").addSpeaker
  const api: typeof import("../api/index").default
  const convertWebMToMP4: typeof import('../utils/ffmpeg').convertWebMToMP4
  const createRef: typeof import('react').createRef
  const deleteSpeaker: typeof import("../api/index").deleteSpeaker
  const deleteUserChat: typeof import("../api/index").deleteUserChat
  const ellipsis: typeof import('../utils/utils').ellipsis
  const formatTime: typeof import('../utils/time').formatTime
  const forwardRef: typeof import('react').forwardRef
  const generateAvatar: typeof import('../utils/utils').generateAvatar
  const getChatData: typeof import("../api/index").getChatData
  const getChattingAi: typeof import("../api/index").getChattingAi
  const getHotAi: typeof import("../api/index").getHotAi
  const getMemoryList: typeof import("../api/index").getMemoryList
  const getRandomDanceAnimation: typeof import('../utils/utils').getRandomDanceAnimation
  const getRoleList: typeof import("../api/index").getRoleList
  const getSpeakerList: typeof import("../api/index").getSpeakerList
  const getTagList: typeof import("../api/index").getTagList
  const getUserChat: typeof import("../api/index").getUserChat
  const getUserInfo: typeof import("../api/index").getUserInfo
  const lazy: typeof import('react').lazy
  const login: typeof import("../api/index").login
  const loginWeb3: typeof import("../api/index").loginWeb3
  const memo: typeof import('react').memo
  const pcmBase64ToAudioUrl: typeof import('../utils/baseToaudio').pcmBase64ToAudioUrl
  const playPCM: typeof import('../utils/baseToaudio').playPCM
  const register: typeof import("../api/index").register
  const request: typeof import("../utils/request").default
  const startTransition: typeof import('react').startTransition
  const svg: typeof import("../utils/svg").default
  const timeFromNow: typeof import('../utils/time').timeFromNow
  const updateSpeaker: typeof import("../api/index").updateSpeaker
  const updateUserInfo: typeof import("../api/index").updateUserInfo
  const useApi: typeof import('../api/index').useApi
  const useAudio: typeof import('../hooks/head/useAudio').default
  const useCallback: typeof import('react').useCallback
  const useCanvasCleaner: typeof import("../hooks/useCanvasCleaner").useCanvasCleaner
  const useCanvasRecorder: typeof import("../hooks/useCanvasRecorder").useCanvasRecorder
  const useConfigStore: typeof import('../store/config').useConfigStore
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDevice: typeof import('../hooks/useDevice').useDevice
  const useEffect: typeof import('react').useEffect
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLang: typeof import('../hooks/useLang').useLang
  const useLangStore: typeof import("../store/lang").useLangStore
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLoadingStore: typeof import('../store/loading').useLoadingStore
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRefCanvasRecorder: typeof import('../hooks/useCanvasRecorder').useRefCanvasRecorder
  const useRequest: typeof import('../hooks/useRequest').default
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useScenes: typeof import('../hooks/head/scenes').useScenes
  const useScreenRecoeding: typeof import("../hooks/useScreenRecoeding").default
  const useScreenRecorder: typeof import("../hooks/useScreenRecoeding").useScreenRecorder
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const useUserStore: typeof import('../store/user').useUserStore
  const useWebmToMp4: typeof import("../hooks/useWebmToMp4").useWebmToMp4
}
// for type re-export
declare global {
  // @ts-ignore
  export type { LoginParams, RegisterParams } from '../api/index'
  import('../api/index')
}
